{"name":"Sign Up Website","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [true] but found [false]","trace":"java.lang.AssertionError: expected [true] but found [false]\n\tat org.testng.Assert.fail(Assert.java:96)\n\tat org.testng.Assert.failNotEquals(Assert.java:776)\n\tat org.testng.Assert.assertTrue(Assert.java:44)\n\tat org.testng.Assert.assertTrue(Assert.java:54)\n\tat tests.phpTraval.SignUpTest.InvalidPhone(SignUpTest.java:56)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\n\tat org.testng.TestRunner.run(TestRunner.java:505)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\n\tat org.testng.TestNG.run(TestNG.java:1017)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\n"},"stage":"finished","description":"Testcase Description : Verify Sign Up","steps":[],"attachments":[{"name":"Page screenshot","source":"42b62d3b-90ef-4da9-a7b7-523f24b6357d-attachment","type":"image/png"},{"name":"InvalidPhone failed and screenshot taken!","source":"cf0eeffc-d1ae-4e53-8fd5-950ccd2880d0-attachment","type":"text/plain"}],"parameters":[],"start":1606971469824,"stop":1606971472490,"uuid":"acd75a5a-61fb-4634-9ce3-73e06cae90fb","historyId":"3e91b2afb822481d10cb609e604d8e23","fullName":"tests.phpTraval.SignUpTest.InvalidPhone","labels":[{"name":"package","value":"tests.phpTraval.SignUpTest"},{"name":"testClass","value":"tests.phpTraval.SignUpTest"},{"name":"testMethod","value":"InvalidPhone"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Selenium-framwork"},{"name":"subSuite","value":"tests.phpTraval.SignUpTest"},{"name":"host","value":"BAEMINs-MacBook-Pro.local"},{"name":"thread","value":"7380@BAEMINs-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"normal"}],"links":[]}